from sqlalchemy.orm import Session

from madplanner.repositories.recipes import RecipeRepository
from madplanner.schemas.recipe import RecipeIngredientInput, RecipeInstructionInput, RecipeWrite
from madplanner.services.recipes import RecipeService


STARTER_RECIPES = (
    RecipeWrite(name="Fluffy breakfast pancakes", description="An easy pancake recipe for a relaxed family breakfast.", servings=4, preparation_time_minutes=10, cooking_time_minutes=20, total_time_minutes=30, cuisine="International", category="Breakfast", tags=["Quick", "Family favorite", "Pancakes"], meal_types=["breakfast", "lunch"], recipe_types=["Breakfast"], ingredients=[RecipeIngredientInput(raw_text=value) for value in ("250 g flour", "2 eggs", "400 ml milk", "1 tbsp sugar", "25 g butter")], instructions=[RecipeInstructionInput(text=value) for value in ("Whisk the flour, eggs, milk, and sugar into a smooth batter.", "Melt a little butter in a frying pan over medium heat.", "Cook each pancake until golden on both sides and serve warm.")]),
    RecipeWrite(name="Creamy tomato pasta", description="A simple weekday pasta with tomato, cream, and spinach.", servings=4, preparation_time_minutes=10, cooking_time_minutes=20, total_time_minutes=30, cuisine="Italian inspired", category="Dinner", tags=["Pasta", "Quick", "Vegetarian"], meal_types=["lunch", "dinner"], recipe_types=["Dinner"], ingredients=[RecipeIngredientInput(raw_text=value) for value in ("400 g pasta", "2 cans chopped tomatoes", "200 ml cooking cream", "150 g spinach", "2 cloves garlic")], instructions=[RecipeInstructionInput(text=value) for value in ("Cook the pasta according to its package instructions.", "Simmer tomatoes, cream, and chopped garlic for 10 minutes.", "Fold in the spinach, combine with the pasta, and season to taste.")]),
    RecipeWrite(name="Sheet-pan salmon and potatoes", description="Salmon, potatoes, and broccoli cooked together on one tray.", servings=4, preparation_time_minutes=15, cooking_time_minutes=30, total_time_minutes=45, cuisine="Nordic inspired", category="Dinner", tags=["Fish", "Potato", "One pan"], meal_types=["lunch", "dinner"], recipe_types=["Dinner"], ingredients=[RecipeIngredientInput(raw_text=value) for value in ("600 g salmon", "800 g potatoes", "1 broccoli", "1 lemon", "2 tbsp olive oil")], instructions=[RecipeInstructionInput(text=value) for value in ("Heat the oven to 200°C and cut the potatoes into small pieces.", "Roast the potatoes with oil for 15 minutes.", "Add salmon and broccoli, then roast for another 15 minutes and serve with lemon.")]),
    RecipeWrite(name="Mexican bean bowls", description="Colorful rice bowls with seasoned beans and fresh toppings.", servings=4, preparation_time_minutes=15, cooking_time_minutes=20, total_time_minutes=35, cuisine="Mexican inspired", category="Dinner", tags=["Mexican", "Rice", "Vegetarian"], meal_types=["lunch", "dinner"], recipe_types=["Dinner"], ingredients=[RecipeIngredientInput(raw_text=value) for value in ("300 g rice", "2 cans black beans", "200 g corn", "2 tomatoes", "1 avocado", "1 lime")], instructions=[RecipeInstructionInput(text=value) for value in ("Cook the rice until tender.", "Warm the beans and corn with your preferred Mexican spices.", "Divide into bowls and top with tomato, avocado, and lime.")]),
    RecipeWrite(name="Apple oat crumble", description="A warm fruit dessert with a crisp oat topping.", servings=6, preparation_time_minutes=15, cooking_time_minutes=35, total_time_minutes=50, cuisine="European", category="Dessert", tags=["Apple", "Baking", "Autumn"], meal_types=[], recipe_types=["Dessert", "Bake-off"], ingredients=[RecipeIngredientInput(raw_text=value) for value in ("6 apples", "150 g oats", "100 g flour", "100 g butter", "75 g sugar", "1 tsp cinnamon")], instructions=[RecipeInstructionInput(text=value) for value in ("Heat the oven to 190°C and slice the apples into a baking dish.", "Rub oats, flour, butter, sugar, and cinnamon together into crumbs.", "Cover the apples with the topping and bake for 35 minutes.")]),
)


def add_starter_recipes(session: Session, family_id: int, user_id: int) -> None:
    service = RecipeService(RecipeRepository(session, family_id), user_id)
    for recipe in STARTER_RECIPES:
        service.create_recipe(recipe)
