import { useState } from 'react'
import QRCode from 'qrcode'
import { useAuth } from '../auth/AuthContext'
import { translator } from '../i18n'

export function MfaSettings() {
  const { account, startMfaEnrollment, confirmMfaEnrollment, disableMfa } = useAuth(); const t = translator(account?.locale)
  const [secret, setSecret] = useState(''); const [qrUrl, setQrUrl] = useState(''); const [code, setCode] = useState(''); const [password, setPassword] = useState(''); const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function start() { setBusy(true); setError(''); try { const enrollment = await startMfaEnrollment(); setSecret(enrollment.secret); setQrUrl(await QRCode.toDataURL(enrollment.provisioning_uri, { width: 220, margin: 1 })) } catch (reason) { setError(reason instanceof Error ? reason.message : t('mfaSetupFailed')) } finally { setBusy(false) } }
  async function confirm() { setBusy(true); setError(''); try { setRecoveryCodes(await confirmMfaEnrollment(code)); setSecret(''); setQrUrl(''); setCode('') } catch (reason) { setError(reason instanceof Error ? reason.message : t('requestFailed')) } finally { setBusy(false) } }
  async function disable() { setBusy(true); setError(''); try { await disableMfa(password); setPassword('') } catch (reason) { setError(reason instanceof Error ? reason.message : t('requestFailed')) } finally { setBusy(false) } }
  return <section className="family-panel mfa-settings"><h2>{t('accountSecurity')}</h2><p>{account?.mfa_enabled ? t('mfaProtected') : t('mfaNotProtected')}</p>{recoveryCodes.length > 0 ? <div className="recovery-codes"><h3>{t('recoveryCodes')}</h3><p>{t('recoveryCodesHelp')}</p><code>{recoveryCodes.join('\n')}</code><div className="form-actions"><button className="button" onClick={() => navigator.clipboard.writeText(recoveryCodes.join('\n'))}>{t('copyCodes')}</button><button className="button button--primary" onClick={() => setRecoveryCodes([])}>{t('savedCodes')}</button></div></div> : account?.mfa_enabled ? <div className="mfa-disable"><label className="field"><span>{t('confirmPassword')}</span><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><button className="button button--danger" disabled={busy || !password} onClick={disable}>{t('disableMfa')}</button></div> : secret ? <div className="mfa-enrollment"><p>{t('scanQr')}</p>{qrUrl && <img src={qrUrl} alt="Authenticator QR code" />}<label className="field"><span>{t('manualSecret')}</span><input readOnly value={secret} /></label><label className="field"><span>{t('authenticationCode')}</span><input inputMode="numeric" autoComplete="one-time-code" value={code} onChange={(event) => setCode(event.target.value)} /></label><button className="button button--primary" disabled={busy || code.length < 6} onClick={confirm}>{t('verifyCode')}</button></div> : <button className="button button--primary" disabled={busy} onClick={start}>{t('enableMfa')}</button>}{error && <div className="notice notice--error" role="alert">{error}</div>}</section>
}
