import { useState, type FormEvent } from 'react'
import type { Account } from '../api/auth'
import { useAuth } from '../auth/AuthContext'
import { rememberedLocale, rememberLocale, translator } from '../i18n'
import './AccountPages.css'

export function AccountAccessPage() {
  const { setupRequired, login, completeMfaLogin, setupOwner } = useAuth(); const [locale, setPageLocale] = useState<Account['locale']>(rememberedLocale); const [email, setEmail] = useState(''); const [displayName, setDisplayName] = useState(''); const [familyName, setFamilyName] = useState(''); const [password, setPassword] = useState(''); const [challengeToken, setChallengeToken] = useState(''); const [code, setCode] = useState(''); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const t = translator(locale)
  const changeLocale = (next: Account['locale']) => { setPageLocale(next); rememberLocale(next) }
  async function submit(event: FormEvent) { event.preventDefault(); setSubmitting(true); setError(''); try { if (challengeToken) await completeMfaLogin(challengeToken, code); else if (setupRequired) await setupOwner({ email, display_name: displayName, password, family_name: familyName }); else { const challenge = await login(email, password); if (challenge) { setChallengeToken(challenge.challenge_token); setPassword('') } } } catch (reason) { setError(reason instanceof Error ? reason.message : t('requestFailed')) } finally { setSubmitting(false) } }
  return <div className="account-shell"><section className="account-card"><div className="brand account-brand"><span className="brand-mark">M</span>Mad Planner</div><label className="field"><span>{t('language')}</span><select value={locale} onChange={(event) => changeLocale(event.target.value as Account['locale'])}><option value="en">English</option><option value="da">Dansk</option><option value="nl">Nederlands</option></select></label><p className="eyebrow">{challengeToken ? t('privateFamilySpace') : setupRequired ? t('welcomeHome') : t('privateFamilySpace')}</p><h1>{challengeToken ? t('mfaChallengeTitle') : setupRequired ? t('createYourFamily') : t('welcomeBack')}</h1><p className="account-intro">{challengeToken ? t('authenticationCodeHelp') : setupRequired ? t('ownerSetupIntro') : t('signInIntro')}</p><form onSubmit={submit}>{challengeToken ? <><label className="field"><span>{t('authenticationCode')}</span><input required autoFocus inputMode="numeric" autoComplete="one-time-code" value={code} onChange={(event) => setCode(event.target.value)} /></label><button className="button" type="button" onClick={() => { setChallengeToken(''); setCode(''); setError('') }}>{t('useDifferentAccount')}</button></> : <>{setupRequired && <><label className="field"><span>{t('yourName')}</span><input required maxLength={120} value={displayName} onChange={(event) => setDisplayName(event.target.value)} autoComplete="name" /></label><label className="field"><span>{t('familyName')}</span><input required maxLength={120} value={familyName} onChange={(event) => setFamilyName(event.target.value)} /></label></>}<label className="field"><span>{t('email')}</span><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" /></label><label className="field"><span>{t('password')}</span><input required minLength={setupRequired ? 10 : 1} type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete={setupRequired ? 'new-password' : 'current-password'} /></label>{setupRequired && <small>{t('passwordHelp')}</small>}</>}{error && <div className="notice notice--error" role="alert">{error}</div>}<button className="button button--primary" disabled={submitting}>{submitting ? t('pleaseWait') : challengeToken ? t('verifyAndSignIn') : setupRequired ? t('createFamily') : t('signIn')}</button></form></section></div>
}
