import { type FormEvent, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { createRecipe, parseServingCount, previewRecipeImport, type ImportedRecipePreview } from '../api/recipes'
import './ImportRecipePage.css'

export function ImportRecipePage() {
  const navigate = useNavigate(); const [url, setUrl] = useState(''); const [preview, setPreview] = useState<ImportedRecipePreview | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function load(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { setPreview(await previewRecipeImport(url)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Import failed') } finally { setBusy(false) } }
  const updateLines = (field: 'ingredients' | 'instructions', value: string) => setPreview((current) => current ? { ...current, [field]: value.split('\n').map((line) => line.trim()).filter(Boolean) } : current)
  async function save() { if (!preview) return; setBusy(true); try { const recipe = await createRecipe({ name: preview.name, description: preview.description || undefined, source_url: preview.source_url, author: preview.author || undefined, servings: parseServingCount(preview.servings), preparation_time_minutes: preview.preparation_time_minutes ?? undefined, cooking_time_minutes: preview.cooking_time_minutes ?? undefined, total_time_minutes: preview.total_time_minutes ?? undefined, cuisine: preview.cuisine || undefined, category: preview.category || undefined, ingredients: preview.ingredients.map((raw_text) => ({ raw_text })), instructions: preview.instructions.map((text) => ({ text })) }); navigate(`/recipes/${recipe.id}`) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Save failed'); setBusy(false) } }
  return <section className="page import-page"><Link className="back-link" to="/recipes">← All recipes</Link><div className="page-heading"><div><p className="eyebrow">Recipe importer</p><h1>Import from a website</h1><p>Paste a recipe URL and review the extracted data before saving.</p></div></div><form className="import-bar" onSubmit={load}><label className="field"><span>Recipe URL</span><input type="url" required value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com/recipe" /></label><button className="button button--primary" disabled={busy}>{busy ? 'Reading…' : 'Preview recipe'}</button></form>{error && <p className="notice notice--error" role="alert">{error}</p>}{preview && <div className="import-preview"><div className="preview-heading"><div><p className="eyebrow">Review extracted recipe</p><input className="title-input" aria-label="Recipe name" value={preview.name} onChange={(event) => setPreview({ ...preview, name: event.target.value })} /></div><span className="parser-badge">{preview.parser}</span></div><label className="field"><span>Description</span><textarea rows={3} value={preview.description || ''} onChange={(event) => setPreview({ ...preview, description: event.target.value })} /></label><div className="preview-grid"><label className="field"><span>Cuisine</span><input value={preview.cuisine || ''} onChange={(event) => setPreview({ ...preview, cuisine: event.target.value })} /></label><label className="field"><span>Category</span><input value={preview.category || ''} onChange={(event) => setPreview({ ...preview, category: event.target.value })} /></label><label className="field"><span>Servings</span><input value={preview.servings || ''} onChange={(event) => setPreview({ ...preview, servings: event.target.value })} /></label></div><div className="recipe-columns"><label className="field"><span>Ingredients — one per line</span><textarea rows={10} value={preview.ingredients.join('\n')} onChange={(event) => updateLines('ingredients', event.target.value)} /></label><label className="field"><span>Instructions — one per line</span><textarea rows={10} value={preview.instructions.join('\n')} onChange={(event) => updateLines('instructions', event.target.value)} /></label></div><div className="form-actions"><button className="button" type="button" onClick={() => setPreview(null)}>Start over</button><button className="button button--primary" type="button" disabled={busy || !preview.name.trim()} onClick={save}>Save imported recipe</button></div></div>}</section>
}
