import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { listRecipeTypes, type RecipeType } from '../api/auth'
import { createRecipe, scanRecipeImage, uploadRecipeImage, type RecipeScanPreview } from '../api/recipes'
import './ImportRecipePage.css'

export function ScanRecipePage() {
  const navigate = useNavigate(); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<RecipeScanPreview | null>(null); const [recipeTypes, setRecipeTypes] = useState<RecipeType[]>([]); const [selectedTypes, setSelectedTypes] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => { listRecipeTypes().then(setRecipeTypes).catch((reason) => setError(reason.message)) }, [])
  const toggleType = (name: string) => setSelectedTypes((current) => current.includes(name) ? current.filter((item) => item !== name) : [...current, name])
  const updateLines = (field: 'ingredients' | 'instructions', value: string) => setPreview((current) => current ? { ...current, [field]: value.split('\n').map((line) => line.trim()).filter(Boolean) } : current)
  async function scan() { if (!file) return; setBusy(true); setError(''); try { setPreview(await scanRecipeImage(file)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'The page could not be scanned.') } finally { setBusy(false) } }
  async function save() { if (!file || !preview || selectedTypes.length === 0) return; setBusy(true); setError(''); const mealTypes = [...new Set(recipeTypes.filter((item) => selectedTypes.includes(item.name)).map((item) => item.meal_type).filter((item): item is NonNullable<typeof item> => item !== null))]; try { let recipe = await createRecipe({ name: preview.name, recipe_types: selectedTypes, meal_types: mealTypes, ingredients: preview.ingredients.map((raw_text) => ({ raw_text })), instructions: preview.instructions.map((text) => ({ text })) }); recipe = await uploadRecipeImage(recipe.id, file); navigate(`/recipes/${recipe.id}`) } catch (reason) { setError(reason instanceof Error ? reason.message : 'The scanned recipe could not be saved.'); setBusy(false) } }
  return <section className="page import-page"><Link className="back-link" to="/recipes">← All recipes</Link><div className="page-heading"><div><p className="eyebrow">Book recipe scanner</p><h1>Scan a recipe page</h1><p>Take a clear, straight photo in good light. Text recognition happens privately inside Mad Planner.</p></div></div><div className="import-bar"><label className="field"><span>Recipe page photo</span><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(event) => { setFile(event.target.files?.[0] || null); setPreview(null) }} /></label><button className="button button--primary" type="button" disabled={!file || busy} onClick={scan}>{busy ? 'Reading…' : 'Scan page'}</button></div>{error && <p className="notice notice--error" role="alert">{error}</p>}{preview && <div className="import-preview"><div className="preview-heading"><div><p className="eyebrow">Review detected recipe</p><input className="title-input" aria-label="Recipe name" value={preview.name} onChange={(event) => setPreview({ ...preview, name: event.target.value })} /></div><span className="parser-badge">OCR</span></div>{preview.warnings.map((warning) => <p className="notice" key={warning}>{warning}</p>)}<section className="type-confirmation"><strong>Choose at least one recipe type</strong><div className="choice-chips">{recipeTypes.map((item) => <button type="button" className={`choice-chip${selectedTypes.includes(item.name) ? ' choice-chip--selected' : ''}`} aria-pressed={selectedTypes.includes(item.name)} onClick={() => toggleType(item.name)} key={item.id}>{item.name}</button>)}</div></section><div className="recipe-columns"><label className="field"><span>Ingredients — one per line</span><textarea rows={12} value={preview.ingredients.join('\n')} onChange={(event) => updateLines('ingredients', event.target.value)} /></label><label className="field"><span>Instructions — one per line</span><textarea rows={12} value={preview.instructions.join('\n')} onChange={(event) => updateLines('instructions', event.target.value)} /></label></div><details><summary>Show all detected text</summary><pre className="scan-raw-text">{preview.raw_text}</pre></details><div className="form-actions"><button className="button" type="button" onClick={() => setPreview(null)}>Scan again</button><button className="button button--primary" type="button" disabled={busy || !preview.name.trim() || selectedTypes.length === 0} onClick={save}>Save scanned recipe</button></div></div>}</section>
}
